### PR TITLE
Attempt API call to retrieve data dynamically.

### PR DESCRIPTION
**Pull request by ecomerford**
@chutten @georgf this is how I've been trying to pull in the sample data after deploying it to the GH pages build. Georg suggested dropping this into a PR so that I can get input on the problem. Currently this code results in no data being parsed and the following error:

```
SyntaxError: JSON.parse: unexpected character at line 1 column 1 of the JSON data
```

I've read through [this](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Errors/JSON_bad_parse?utm_source=mozilla&utm_medium=firefox-console-errors&utm_campaign=default) documentation on the error type; it basically says that error is telling me that the file is not a valid JSON. 

I'm able to successfully import the data using a local file path, so it appears that there's nothing wrong with the format of the data itself, but the way that I'm retrieving it.

### CODE REVIEW

**Comment by chutten** [comment]
It appears as though the data files aren't being deployed. When I try to `fetch()` `https://mozilla.github.io/mdv2/GC_MS_nightly_62.json` it returns 404. Don't the data files need to be somewhere under `public/` for react to include them in the final build?

**Comment by ecomerford** [comment]
Ohh, you're right about the 404 error. I should have checked that. Not a parsing issue, then. 

The data is in the `public` directory now, but the fetch doesn't work for the same reason. For instance, `https://mozilla.github.io/mdv2/public/data/GC_MS_nightly_62.json` returns 404 🤔

**Comment by badboy** [comment]
The correct URL would be https://mozilla.github.io/mdv2/data/GC_MS_nightly_62.json

**Comment by ecomerford** [comment]
Okay, I've got it working now. Thanks @badboy and @chutten!

**Pull request closed without merging**
