### PR TITLE
Add Travis file and homepage

### PR DESCRIPTION
**Pull request by ecomerford**
@chutten these changes should enable Travis CI to build the project and host it on GitHub pages.

### CODE REVIEW

**Comment by badboy** [comment]
Did you set the env variable "github_token" on Travis already?
The alternative is to put it encrypted into the .travis.yml itself: https://docs.travis-ci.com/user/encryption-keys/

**Comment by ecomerford** [comment]
@badboy yes, I gave it a github_token variable. Is the alternative preferable?

**Comment by badboy** [comment]
@ecomerford I like it as it keeps all config in a single file instead of having part of it hidden in some service settings (sorry for not linking to the appropiate docs on that before)

**Comment by ecomerford** [comment]
Cool, I'll update that today. Thanks!

**Review by chutten — APPROVED** [review]

**Pull request merged**
